schema_version = "1.0.0"

id = "botw_importer"
version = "0.0.1"
name = "BotW Import/Cleanup"
tagline = "Automate import tasks for BotW"
maintainer = "Community"
type = "add-on"
website = "blender.org"
tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
[permissions]
files = "Load .dae/.fbx/.png/.jpg/.blend files from disk"
