schema_version = "1.0.0"

id = "botw_importer"
version = "0.0.1"
name = "BotW Asset Importer"
tagline = "Import assets and world of BotW"
maintainer = "Community"
type = "add-on"
website = "blender.org"
tags = ["Import-Export"]

blender_version_min = "4.4.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
wheels = [
   "./wheels/tqdm-4.67.1-py3-none-any.whl",
]
[permissions]
files = "Load .dae/.fbx/.png/.jpg/.blend files from disk"
